SELECT
    last_name
    || ' ' || job_id AS "EMPLEADO"
FROM
    employees;

--

SELECT DEPARTMENT_ID, LISTAGG(FIRST_NAME, ',') WITHIN GROUP (ORDER BY FIRST_NAME)AS employees
FROM   EMPLOYEES
WHERE DEPARTMENT_ID = 30
GROUP BY DEPARTMENT_ID;
